name: IntelliDoors
version: 1.1.11
description: Intelligent door manipulation plugin.
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-intellidoors/
main: com.moltendorf.bukkit.intellidoors.Plugin
